[versions]
android = "4.1.1.4"
animalSniffer = "1.16"
animalSnifferGradle = "1.5.0"
assertj = "3.11.0"
coroutines = "1.5.2"
dokka = "1.5.30"
grpc = "1.44.1"
gson = "2.9.0"
guava = "31.1-jre"
javapoet = "1.13.0"
jimfs = "1.0"
jmh = "1.34"
jsr305 = "3.0.2"
junit = "4.13.2"
kotlin = "1.6.10"
kotlinpoet = "1.10.2"
ktlint = "0.42.1"
moshi = "1.13.0"
okhttp = "4.9.3"
okio = "3.0.0"
protobuf = "3.19.4"
protobufGradlePlugin = "0.8.18"

[libraries]
android = { module = "com.google.android:android", version.ref = "android" }
androidx-annotations = { module = "androidx.annotation:annotation", version = "1.1.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.0.2" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version = "1.1.3" }
androidx-ktx = { module = "androidx.core:core-ktx", version = "1.0.2" }
dokka-core = { module = "org.jetbrains.dokka:dokka-core", version.ref = "dokka" }
dokka-gradlePlugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
grpc-netty = { module = "io.grpc:grpc-netty", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
okio-bom = { module = "com.squareup.okio:okio-bom", version.ref = "okio" }
okio-core = { module = "com.squareup.okio:okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem" }
swiftpoet = { module = "io.outfoxx:swiftpoet", version = "1.3.1" }
wire-compiler = { module =  "com.squareup.wire:wire-compiler" }
wire-gradlePlugin = { module =  "com.squareup.wire:wire-gradle-plugin" }
wire-grpcClient = { module =  "com.squareup.wire:wire-grpc-client" }
wire-grpcMockWebServer = { module =  "com.squareup.wire:wire-grpc-mockwebserver" }
wire-grpcServer = { module =  "com.squareup.wire:wire-grpc-server" }
wire-gsonSupport = { module =  "com.squareup.wire:wire-gson-support" }
wire-javaGenerator = { module =  "com.squareup.wire:wire-java-generator" }
wire-kotlinGenerator = { module =  "com.squareup.wire:wire-kotlin-generator" }
wire-moshiAdapter = { module =  "com.squareup.wire:wire-moshi-adapter" }
wire-runtime = { module =  "com.squareup.wire:wire-runtime" }
wire-schema = { module =  "com.squareup.wire:wire-schema" }
wire-schemaHandlerTests = { module =  "com.squareup.wire:wire-schema-tests" }
wire-testUtils = { module =  "com.squareup.wire:wire-test-utils" }
